name: macos

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/macos.yml'
      - 'tests/**'
      - '**/*.lua'

  pull_request:
    paths:
      - '.github/workflows/macos.yml'
      - 'tests/**'
      - '**/*.lua'

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: mymindstorm/setup-emsdk@v14

    - name: install premake5
      uses: Jarod42/install-premake5@v6

    - name: install ninja
      uses: seanmiddleditch/gha-setup-ninja@v6

    - name: Versions
      run: |
        python --version
        premake5 --version
        ninja --version

    - name: test projects
      run: cd tests && python run_tests.py

