name: windows

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/windows.yml'
      - 'tests/**'
      - '**/*.lua'

  pull_request:
    paths:
      - '.github/workflows/windows.yml'
      - 'tests/**'
      - '**/*.lua'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: mymindstorm/setup-emsdk@v14

    - name: install premake5
      uses: Jarod42/install-premake5@v6

    - name: install ninja
      uses: seanmiddleditch/gha-setup-ninja@v6

    - name: Versions
      run: |
        python --version
        premake5 --version
        ninja --version

    - name: Add cl.exe to PATH
      uses: ilammy/msvc-dev-cmd@v1

    - name: test projects
      run: cd tests && python run_tests.py
      shell: bash
